#!/usr/bin/env bash
# PreToolUse: blocks edits to auto-generated files.
# Input: hook JSON via stdin
# Output: exit 0 (allow) or exit 2 (block)

set -euo pipefail

payload=$(cat)

file_path=$(printf '%s' "$payload" | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
    p = d.get("tool_input", {}).get("file_path") or d.get("tool_input", {}).get("notebook_path") or ""
    print(p)
except Exception:
    print("")
')

if [[ -z "$file_path" ]]; then
  exit 0
fi

case "$file_path" in
  */po/messages.pot)
    echo "BLOCKED: po/messages.pot is auto-generated by extract-messages.sh. Do not edit by hand." >&2
    echo "To add new msgids, modify src/*.md and run ./scripts/sync-translations.sh." >&2
    exit 2
    ;;
  */book/*|*/book/ru/*|*/book/en/*)
    echo "BLOCKED: book/ is the mdBook output directory (auto-generated)." >&2
    echo "Source lives in src/*.md. Build with: mdbook build." >&2
    exit 2
    ;;
  */translations/*.json.tmp)
    echo "BLOCKED: *.json.tmp is a half-processed translation batch — not for commit." >&2
    exit 2
    ;;
esac

exit 0
